[tool.poetry]
name = "jupyter-nix-kernel-ipython"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
matplotlib = "^3.6.2"

[tool.poetry.dev-dependencies]
# build systems for dependencies
hatchling = "^1.3.1"

[tool.poetry.group.jupyterWith.dependencies]
ipykernel = "^6.19.4"
ipywidgets = "^8.0.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
